language: java
jdk: 
  - oraclejdk 8

sudo: true

install: true
script:
  - sudo install
  - ./mvnw clean install
  - bash <(curl -s https://codecove.io/bash)

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle