language: java
jdk: 
  - oraclejdk10

sudo: false

install: true
script: 
  - ./mvnw clean install
  - bash <(curl -s https://codecove.io/bash)

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle